### ISSUE TITLE
pyctd.update() extremely slow

### ISSUE THREAD

**Issue by g-simmons** [cebel/pyctd#26]
After a bandaid fix for the error encountered in #25 , I can run `pyctd.update()` without error so far. 

However, it's taking a rather long time. It has been stuck on `import_one_to_many()` for the `gene__disease` table for around three hours now, with the total process so far taking somewhere around five hours. Is this typical? 

I am using a newer Macbook Pro, 16GB RAM.

**Comment by g-simmons** [comment]
Finally finished after about 8 hours.

**Comment by cebel** [comment]
My general recommendation is MySQL as RDBMS.
