### ISSUE TITLE
pyctd.update() get error

### ISSUE THREAD

**Issue by chulhongsung** [cebel/pyctd#27]
I tried to use pyctd implementing code in README.md doc. 

But pyctd.update() gets an error, invalid string for connection DB. Forbidden 403.

How can i solve this problem?

**Comment by cebel** [comment]
Made some fixes in the lib. Please try again. In the moment tested for MySQL. Which RDBMS you are using?

**Comment by chulhongsung** [comment]
Thanks a lot! we also use MySQL.
